name: pull request comment github actions

on:
  issue_comment:
    types: [created, edited]

jobs:
  check_comment:
    name: Judge release comment
    runs-on: ubuntu-latest
    env:
      BUMPUP: fromJSON('["major", "minor", "patch"]')

    steps:
      - name: check comment
        uses: xt0rted/slash-command-action@065da288bcfe24ff96b3364c7aac1f6dca0fb027 #1.1.0
        id: command
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: release
          reaction: true
          reaction-type: eyes
          allow-edits: false
          permission-level: write
      - name: Git settings
        run: |
          git config --global user.name release-machine
          git config --global user.email email@example.com
      - name: release request
        if: contains(${BUMPUP}, ${{steps.command.outputs.command-arguments}})
        uses: xt0rted/slash-command-action@065da288bcfe24ff96b3364c7aac1f6dca0fb027 #1.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: release
          reaction: true
          reaction-type: rocket
          allow-edits: false
          permission-level: write

      - name: get brach name
        if: contains(${BUMPUP}, ${{steps.command.outputs.command-arguments}})
        uses: xt0rted/pull-request-comment-branch@f2f07162618551540507cbd00ddf16ffcaa0c72f #1.3.0
        id: comment-branch

      - name: checkout
        uses: actions/checkout@v2
        if: contains(${BUMPUP}, ${{steps.command.outputs.command-arguments}})
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - name: post release comment
        if: contains(${BUMPUP}, ${{steps.command.outputs.command-arguments}})
        uses: actions/github-script@v5
        env:
          MESSAGE: ${{ steps.command.outputs.command-arguments }} にてリリースを行います。
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.MESSAGE
            })

      - name: release commit
        if: contains(${BUMPUP}, ${{steps.command.outputs.command-arguments}})
        run: |
          git commit --allow-empty -m "bump up version ${{ steps.command.outputs.command-arguments }}"
          git push
