name: target main pull request github actions

on:
  push:
    branches:
      - main

jobs:
  release:
    name: auto release to GitHub Release
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELEASE_IT_VERSION: 14.11.6
    steps:
      - name: Check out codes
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Set release settings
        run: |
          git config --global user.name release-machine
          git config --global user.email email@example.com
      - name: install packages
        run: |
          npm install -g release-it@${RELEASE_IT_VERSION}
      - name: Major release
        id: major
        if: contains(toJSON(github.event.commits.*.message), 'bump up version major')
        run: release-it -- major --ci
      - name: Minor release
        id: minor
        if: steps.major.conclusion == 'skipped' && contains(toJSON(github.event.commits.*.message), 'bump up version minor')
        run: release-it -- minor --ci
      - name: Patch release
        id: patch
        if: "!(steps.major.conclusion == 'success' || steps.minor.conclusion == 'success')"
        run: release-it -- patch --ci
